# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    # Test name: Test1
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://www.autoklad.ua/")
    # 2 | setWindowSize | 1550x838 | 
    self.driver.set_window_size(1550, 838)
    # 3 | click | css=.o-profile > .uk-visible\@s | 
    self.driver.find_element(By.CSS_SELECTOR, ".o-profile > .uk-visible\\@s").click()
    # 4 | click | name=login | 
    self.driver.find_element(By.NAME, "login").click()
    # 5 | type | name=login | 0939279074
    self.driver.find_element(By.NAME, "login").send_keys("0939279074")
    # 6 | type | name=password | 123654
    self.driver.find_element(By.NAME, "password").send_keys("123654")
    # 7 | click | css=.uk-grid-margin > .uk-button | 
    self.driver.find_element(By.CSS_SELECTOR, ".uk-grid-margin > .uk-button").click()
    # 8 | click | css=.uk-visible\@s > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".uk-visible\\@s > span").click()
    # 9 | click | linkText=Мои автомобили | 
    self.driver.find_element(By.LINK_TEXT, "Мои автомобили").click()
    # 10 | click | linkText=Список заказов и оплат | 
    self.driver.find_element(By.LINK_TEXT, "Список заказов и оплат").click()
    # 11 | click | css=.nice-select:nth-child(3) | 
    self.driver.find_element(By.CSS_SELECTOR, ".nice-select:nth-child(3)").click()
    # 12 | click | css=.open | 
    self.driver.find_element(By.CSS_SELECTOR, ".open").click()
    # 13 | click | id=date | 
    self.driver.find_element(By.ID, "date").click()
    # 14 | type | id=date | 26.03.2019
    self.driver.find_element(By.ID, "date").send_keys("26.03.2019")
    # 15 | click | css=.uk-width-1-1 > .uk-button | 
    self.driver.find_element(By.CSS_SELECTOR, ".uk-width-1-1 > .uk-button").click()
    # 16 | click | css=.uk-visible\@s > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".uk-visible\\@s > span").click()
    # 17 | click | linkText=Выход | 
    self.driver.find_element(By.LINK_TEXT, "Выход").click()
  
